### ISSUE TITLE
summaryReport output is a HTML, not a Github markdown

### ISSUE THREAD

**Issue by sergey-krakos-gl** [MishaKav/pytest-coverage-comment#116]
Hello,
I've tried to use this action and have one question.
summaryReport output parameter is specified as "**Markdown** with summaryof: Tests/Skipped/Failures/Errors/Time"
That is meant do be actually HTML, not Github Markdown? Because for now it is HTML and I can't write it to the Job summary.

Thank you

**Comment by MishaKav** [comment]
I found some workaround for this problem, you can see it in this thread https://github.com/MishaKav/pytest-coverage-comment/issues/90#issuecomment-1285917469

```yaml
- name: Add Summary
  uses: actions/github-script@v6
  with:
    script: |
      core.summary.addRaw(${{ steps.coverageComment.outputs.summaryReport }}).write()
```

**Comment by sergey-krakos-gl** [comment]
Great workaround. But I was unable to do the same, commenting PR.

**Comment by PJ-Schulz** [comment]
In my case I want to use `marocchino/sticky-pull-request-comment@v2` to do the comment, because it will be recreated every time at the bottom of the PR and I can add some more informations to the comment.
I found a way to extract the `summaryReport` so that it results in a correct markdown which Github can render.


```yaml
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: coverage/coverage.xml
          junitxml-path: coverage/junitxml.xml
          coverage-path-prefix: my_package/
          hide-comment: true

      - name: Convert coverage comment to valid markdown
        run: |
          echo -en ${{ steps.coverageComment.outputs.summaryReport }} > coverage-comment.md
          sed -i 's/\\"/"/g' coverage-comment.md

      - name: Add detailed information's to the comment
        shell: bash
        continue-on-error: true
        run: |  # here you can execute commands for adding some additional text to the comment
          echo "Hello World" >> coverage-comment.md

      - name: Add PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: coverage-comment.md
```
