### ISSUE TITLE
Some output values return empty

### ISSUE THREAD

**Issue by 0x78f1935** [MishaKav/pytest-coverage-comment#117]
Weirdly enough my output variables are empty. I'm sending the test results into MS-Teams.

<img width="118" alt="image" src="https://user-images.githubusercontent.com/14298262/219220781-39a31ee3-a1ff-4eb8-8bac-f2be1e7cb22b.png">

<img width="310" alt="image" src="https://user-images.githubusercontent.com/14298262/219220814-d8752e6f-d843-4490-a99e-f503a8243ea0.png">

The comment itself seems to generate nicely.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/14298262/219221189-44b40267-1aa0-4e9c-b976-8e8cd138a2e3.png">

The coverage step:
```
    - name: Pytest Coverage Comment
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@v1.1.45
      with:
        pytest-xml-coverage-path: ./htmlcov/coverage.xml
        title: PyTest Coverage
        badge-title: PyTest Coverage
        default-branch: ${{ github.ref }}
```

Am I missing something?
