### ISSUE TITLE
Links in the coverage report linking to non-existent lines of code  getting a 404

### ISSUE THREAD

**Issue by jwestw** [MishaKav/pytest-coverage-comment#125]
On our project I have implemented pytest-coverage-comment, so the coverage report is appearing in the comments on PRs. It's working quite well. 

However, we notice that in the "Missing" column of the coverage report, there are links to lines of code (presumably where there are functions with no tests). However, all these links do not work and lead to a 404. Please see this example:

https://github.com/ONSdigital/research-and-development/pull/13#issuecomment-1486615453

Is this a bug, or have I configured something wrongly?

**Comment by MishaKav** [comment]
Thanks for the public link, it helped me to debug your case.
it's a common use case, your files are inside the directory `src/` try to add the property `coverage-path-prefix` [docs](https://github.com/MishaKav/pytest-coverage-comment#inputs)

```yaml
- name: Pytest coverage comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    pytest-coverage-path: ./pytest-coverage.txt
    coverage-path-prefix: src/
```
