### ISSUE TITLE
File read successfully "/home/runner/work/repo-name/repo-name/./pytest-coverage.txt" Error: Coverage file "/home/runner/work/repo-name/repo-name/./pytest-coverage.txt" has bad format or wrong data

### ISSUE THREAD

**Issue by NorhanAlg** [MishaKav/pytest-coverage-comment#146]
when i run pytest, i don't get any warrnings

  
  This is the command i use for pytest
        pytest -v --color=yes --cov-report "xml:coverage.xml" --junitxml=pytest.xml --cov=. tests/integration_tests/ | tee pytest-coverage.txt

this is the comment section
```
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: pytest-coverage.txt
        junitxml-path: pytest.xml

```
i keep getting from generating the comment
File read successfully "/home/runner/work/repo-name/repo-name/./pytest-coverage.txt"
Error: Coverage file "/home/runner/work/repo-name/repo-name/./pytest-coverage.txt" has bad format or wrong data
