### ISSUE TITLE
There is no test summary in comment

### ISSUE THREAD

**Issue by sangmoon-park** [MishaKav/pytest-coverage-comment#16]
I need a collapsible table so I want to use your action . 
However, when I tested it, the test summary was not shown in the comments. 
Is it not functionally provided? Or should I give an extra option?

My project's github yml is below. pytest version is `5.4.3`

```yml
- name: Run pytest
  run: |
    poetry run pytest --cov=test/ | tee pytest-coverage.txt

- name: Comment coverage
  uses: MishaKav/pytest-coverage-comment@v1.1.3
  with:
    pytest-coverage-path: ./pytest-coverage.txt
```

Expected comment:

![스크린샷 2021-07-12 오후 5 11 51](https://user-images.githubusercontent.com/63227061/125253430-5cd1f400-e334-11eb-8cce-15321b671b5c.png)

Actual comment:

![스크린샷 2021-07-12 오후 5 11 28](https://user-images.githubusercontent.com/63227061/125253475-6a877980-e334-11eb-9d22-49ae708a3bf2.png)

**Comment by MishaKav** [comment]
It's an extra option, for test summary, you should provide `junitxml-path` (to generate it just pass `--junitxml=pytest.xml`)
Here is the code for you:

```yaml
- name: Run pytest
  run: |
    poetry run pytest --junitxml=pytest.xml --cov=test/ | tee pytest-coverage.txt

- name: Comment coverage
  uses: MishaKav/pytest-coverage-comment@v1.1.3
  with:
    pytest-coverage-path: ./pytest-coverage.txt
    junitxml-path: ./pytest.xml
```

**Comment by sHooPmyWooP** [comment]
I have a similar problem when inserting the Report to the README.md
I was following your instruction, where your replace the tags
```
<!-- Pytest Coverage Comment:Begin -->
<!-- Pytest Coverage Comment:End -->
```
With 
```
- name: Update Readme with Coverage Html
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

```
I do get 
![image](https://user-images.githubusercontent.com/37713498/141123697-4693c483-92b8-42bc-901e-e3796136db7f.png)
would expect the test summary to be included, though. Like so
![image](https://user-images.githubusercontent.com/37713498/141123814-6a1592aa-8674-4796-8b7f-570356c180e7.png)

Am I doing sth. wrong?

**Comment by MishaKav** [comment]
You did everything right, I'm not adding `summaryReport` to the output. 
I release a new version when I'm added `summaryReport` to the output (#33 #34 #35). I also update the [workflow](https://github.com/MishaKav/pytest-coverage-comment/blob/main/.github/workflows/update-coverage-on-readme.yml), there are some changes to do what you want.
Use the latest version `uses: MishaKav/pytest-coverage-comment@v1.1.12` or `uses: MishaKav/pytest-coverage-comment@main`, then change to this to achieve your goal:

```yaml
- name: Create Variable of Summary Report
  id: summary_report
  run: |
    SUMMARY_REPORT=${{ steps.coverageComment.outputs.summaryReport }}
    echo "::set-output name=content::$SUMMARY_REPORT"

- name: Update Readme with Coverage Html
  if: ${{ github.ref == 'refs/heads/main' }}
  run: |
    sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n${{ steps.summary_report.outputs.content }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
```
