### ISSUE TITLE
Failure to parse cov report

### ISSUE THREAD

**Issue by math280h** [MishaKav/pytest-coverage-comment#170]
pytest=8.1.1
pytest-cov=4.1.0

seems to return the following when trying to comment:
```
File read successfully "coverage.xml"
Error: Coverage file "coverage.xml" has bad format or wrong data
```

Command:
```
pytest tests/ --cov-fail-under=100 --cov-report=term-missing:skip-covered --cov-report xml:coverage.xml
```

**Comment by MishaKav** [comment]
can you please provide the config that you pass to `pytest-coverage-comment` action?

**Comment by math280h** [comment]
> can you please provide the config that you pass to `pytest-coverage-comment` action?

```
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        if: always()
        with:
          pytest-coverage-path: coverage.xml
          junitxml-path: junit.xml
          create-new-comment: true
          junitxml-title: 'Tests'
```
