### ISSUE TITLE
How to make multiple comments in a PR

### ISSUE THREAD

**Issue by bmmcq** [MishaKav/pytest-coverage-comment#189]
in my project, I use two workflows to run different unit tests and generate code coverages, for example,  
``` 
# the first yml file: 
name: first

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit_tests:
    timeout-minutes: 10
    steps:
        # ...
        uses: MishaKav/pytest-coverage-comment@v1.1.50
        with:
            pytest-coverage-path: ./a/pytest-coverage.txt
            junitxml-path: ./a/pytest.xml
            title: "A UT CodeCoverage"
            badge-title: "A Coverage"

#the second yml file: 
name: second

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit_tests:
    timeout-minutes: 10
    steps:
        # ...
        uses: MishaKav/pytest-coverage-comment@v1.1.50
        with:
            pytest-coverage-path: ./b/pytest-coverage.txt
            junitxml-path: ./b/pytest.xml
            title: "B UT CodeCoverage"
            badge-title: "B Coverage"

```

Although using different titles, the second comment still overwrote the first comment, how to keep two comments and let new pushes to this PR only update old comments;
