### ISSUE TITLE
Fail action based on coverage value?

### ISSUE THREAD

**Issue by shlomiLan** [MishaKav/pytest-coverage-comment#190]
Hey,

Thanks for this useful actions. Can I fail the action if the `coverage` value is under a value? to indicate if a PR lowered the coverage too much?

Thanks

**Comment by MishaKav** [comment]
yes, you may fail the action manually, for example, if your coverage is 85%, so the fail step will look like:

```yaml
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./data/pytest-coverage.txt

      - name: Get coverage value
        run: echo "COVERAGE=$(echo '${{ steps.coverageComment.outputs.coverage }}' | sed 's/%//')" >> $GITHUB_ENV

      - name: Fail job
        if: env.COVERAGE < 86
        run: |
          echo "::error::Coverage don't meet the criteria of 85%"
          exit 1
```
