### ISSUE TITLE
Can you please support coverage.py

### ISSUE THREAD

**Issue by inkeros-gtawaf** [MishaKav/pytest-coverage-comment#199]
``I'm working using coverage for my coverage and the report is generated is basically the same as pytest-cov with one line missing 

```
Name                                   Stmts   Miss  Cover   Missing
--------------------------------------------------------------------
commissions/models.py                     16      2    88%   17, 32
general/models.py                         64      6    91%   73, 86, 102, 116, 130, 142
general/views.py                          18      9    50%   17-32, 39-40
inkeros/settings.py                       55      1    98%   103
inkeros/urls.py                           10      5    50%   36-47
members/models.py                        113     60    47%   79-83, 90-125, 132-145, 156-202, 210-214, 220
members/templatetags/members_tags.py      52     11    79%   19-20, 28, 36, 50, 58, 66-71
members/views.py                         185    104    44%   44-50, 58-64, 119-124, 139-208, 216-239, 247-262, [27](https://github.com/inkeros-solution-dev/osp-platform-dev/actions/runs/13532155947/job/37816619049#step:7:28)6, 289
offices/models.py                         49      5    90%   41, 78, 108-111
offices/views.py                          17      8    53%   16-19, 26-31
products/models.py                        64      6    91%   24, 52, 91, 115, 136, 157
sales/models.py                           91     17    81%   61-62, 68, 74-76, 80, 147-150, 153, 241-248
--------------------------------------------------------------------
TOTAL                                    812    2[34](https://github.com/inkeros-solution-dev/osp-platform-dev/actions/runs/13532155947/job/37816619049#step:7:35)    71%
```

I was wondering if it is possible to support this type as it would be great
pytest-conv allows only one app per time but I have multiple apps and I want them all to be included 

I had to do a workaround for now, it works fine :P 
```
  # Move into the Django project folder (./app) and run pytest
      - name: Test with pytest
        run: coverage run -m pytest --junitxml=coverage.xml
      - name: Generate Coverage Report
        run: |
          coverage report --fail-under=70 --show-missing --skip-covered | tee pytest-coverage.txt
          echo "---------- coverage: platform linux, python 3.12.6-final-0 -----------" > pytest-coverage-tmp.txt
          cat pytest-coverage.txt >> pytest-coverage-tmp.txt
          mv pytest-coverage-tmp.txt pytest-coverage.txt

      - name: Pytest coverage comment
        if: github.event_name == 'pull_request'
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./coverage.xml
```
