### ISSUE TITLE
workflow_dispatch usage

### ISSUE THREAD

**Issue by megetron3** [MishaKav/pytest-coverage-comment#201]
just trying to figure out  the correct usage of the workflow_dispatch. tryin this and more but the reports not generated on the pr page:

```
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
        default: 1321
```
