### ISSUE TITLE
"Resource not accessible by integration" on forks

### ISSUE THREAD

**Issue by vakker** [MishaKav/pytest-coverage-comment#30]
Hi, 
If the action is run from a fork then it raises `Resource not accessible by integration`.
It seems to be related to [this](https://github.com/actions/first-interaction/issues/10) issue.

Maybe with the `set-output` feature (see [here](https://docs.github.com/en/actions/learn-github-actions/workflow-commands-for-github-actions#setting-an-output-parameter)) the files could be directly piped to the comment step instead of writing to a file.

**Comment by MishaKav** [comment]
Can you be more specific? Or maybe you can share an example of what are you trying to do?

**Comment by vakker** [comment]
So for example [this](https://github.com/mgarciaortiz/simple-playgrounds/runs/4002956385?check_suite_focus=true) test run shows the issue.

**Comment by MishaKav** [comment]
As I can see from your log, it successfully generated all data, but when it tries to put a comment it gets `status: 403` - it's meaning your `GITHUB_TOKEN` didn't have permission to create comments. You can read more in [Automatic token authentication](https://docs.github.com/en/actions/security-guides/automatic-token-authentication).
What you can do is create the right token and pass it to params

```yaml
- name: Pytest coverage comment
   uses: MishaKav/pytest-coverage-comment@main
   with:
     token: {{ secrets.GITHUB_TOKEN }}
     pytest-coverage-path: ./pytest-coverage.txt
     junitxml-path: ./pytest.xml
     hide-report: true
``` 

or specify the [permissions](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions) for default `GITHUB_TOKEN` in your workflow:

```yaml
on:
  push:
    branches: [ master ]
permissions: read-all|write-all
```
