### ISSUE TITLE
scheduled test failing with cannot read 'full_name' of undefined

### ISSUE THREAD

**Issue by muleyashutosh** [MishaKav/pytest-coverage-comment#37]
when a scheduled test runs, the pytest coverage comment step is throwing a error
```
TypeError: Cannot read property 'full_name' of undefined
    at main (/home/runner/work/_actions/MishaKav/pytest-coverage-comment/main/dist/index.js:13576:44)
    at /home/runner/work/_actions/MishaKav/pytest-coverage-comment/main/dist/index.js:13718:1
    at /home/runner/work/_actions/MishaKav/pytest-coverage-comment/main/dist/index.js:13723:3
    at Object.<anonymous> (/home/runner/work/_actions/MishaKav/pytest-coverage-comment/main/dist/index.js:13726:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
Error: Cannot read property 'full_name' of undefined
```
Below is the step from github actions file.

```
  name: Pytest coverage output
  id: coverage_comment
  uses: MishaKav/pytest-coverage-comment@main
  if: ${{ always() && github.ref == 'refs/heads/master' }}
  with:
    hide-comment: true
    pytest-coverage-path: ./pytest-coverage.txt
    junitxml-path: ./test-reports/report.xml
 ```
