### ISSUE TITLE
If `--cov-branch` is used then the coverage percent is incorrect

### ISSUE THREAD

**Issue by Andrew-Sheridan** [MishaKav/pytest-coverage-comment#45]
A coverage report generated with the `--cov-branch` flag causes the reported coverage percent / the badge to be incorrect.

For example using `--cov-branch --cov-report=term-missing` creates a table like this.
```text
Name                                                 Stmts   Miss Branch BrPart     Cover   Missing
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
TOTAL                                                  360    194    100      5    45.43%
```

Which causes this badge to be produced:
<img alt="Coverage" src="https://img.shields.io/badge/Coverage-10025-brightgreen.svg" />

**Comment by Andrew-Sheridan** [comment]
Looks like this block does not expect the two extra columns `Branch` and `BrPart`

https://github.com/MishaKav/pytest-coverage-comment/blob/10582b229d9a73436d4bd180fe931dc33ab52bc4/src/parse.js#L145-L151

**Comment by MishaKav** [comment]
Your request was implemented, you can just run `MishaKav/pytest-coverage-comment@main` or use `MishaKav/pytest-coverage-comment@v1.1.18`
Thank you.

**Comment by Andrew-Sheridan** [comment]
Thank you very much for implementing this change so quickly.

When the action is triggered it throws this error:
```
Error: Generating coverage report. parsedLine.at is not a function
```


I really appreciate your efforts on building out this Action, thank you again

**Comment by Andrew-Sheridan** [comment]
If it helps, this is the job from the workflow:
```yaml
  publish-coverage:
    name: 💬 annotate / code coverage
    runs-on: ubuntu-latest
    if: success()
    needs: test
    steps:
      - name: Download Coverage
        uses: actions/download-artifact@v2
        with:
          name: pytest-coverage
          path: results

      - name: Publish Code Coverage
        uses: MishaKav/pytest-coverage-comment@main
        with:
          multiple-files: |
            3.7 Coverage, results/coverage-3.7.txt, results/pytest-3.7.xml
            3.8 Coverage, results/coverage-3.8.txt, results/pytest-3.8.xml
            3.9 Coverage, results/coverage-3.9.txt, results/pytest-3.9.xml
            3.10 Coverage, results/coverage-3.10.txt, results/pytest-3.10.xml
```
