### ISSUE TITLE
0 cover and 100% missing lines in files with 100% cover

### ISSUE THREAD

**Issue by jhonatan-lopes** [MishaKav/pytest-coverage-comment#53]
Hi, 

This is the output of my `pytest` (run with Tox):

```
  ---------- coverage: platform linux, python 3.10.2-final-0 -----------
  Name                     Stmts   Miss Branch BrPart  Cover   Missing
  --------------------------------------------------------------------
  src/schedule/header.py      50      0     16      0   100%
  src/schedule/pdf.py         16      0      2      0   100%
  src/schedule/utils.py       53      1     22      2    96%   120, 134->133
  --------------------------------------------------------------------
  TOTAL                      119      1     40      2    98%
  
  ```
  
As you can see, both `src/schedule/header.py` and `src/schedule/pdf.py` have 100% coverage and, thus, have no missing lines. However, the actions bot show 100% missing lines and 0 cover on the comment:

![image](https://user-images.githubusercontent.com/61277874/157909408-f32419e5-485c-4c39-99d9-106cd1395e53.png)

The `pytest` command that I'm running is:

```shell
pytest -v --color=yes --junitxml=pytest.xml --cov-append --cov-report=term-missing --cov-branch --cov=src tests/ | tee pytest-coverage.txt
```
and my GitHub step:

```yaml
name: Test and Lint

on:
  workflow_dispatch:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:
  test:
    name: Test and Code Coverage Report
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions coverage

    - name: Test with tox
      run: tox
    
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: pytest-coverage.txt
        junitxml-path: pytest.xml
```

Is this normal? Am I missing some configuration on my end?
