### ISSUE TITLE
The head commit for PR event is not ahead of the base commit.

### ISSUE THREAD

**Issue by withchristopher** [MishaKav/pytest-coverage-comment#57]
Received the following error when running this GH Action:

![Screenshot 2022-03-29 at 16 59 05](https://user-images.githubusercontent.com/6439444/160641614-67f8c619-0479-4b1f-bec3-dc50250cc4f7.png)

**Comment by MishaKav** [comment]
- Can you please share more details on your workflow?
- Can you please try to re-run it again on a different branch?

**Comment by withchristopher** [comment]
![Screenshot 2022-04-05 at 10 44 00](https://user-images.githubusercontent.com/6439444/161714964-a784f102-2e5a-434e-a866-41b590e94261.png)


Here is the workflow:

```
 publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build-and-test
    runs-on: self-hosted
    if: always()
    timeout-minutes: 20

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/unit-test-py38/*.xml

      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-results

      - name: Pytest coverage comment in pull-request
        uses: MishaKav/pytest-coverage-comment@main
        with:
          default-branch: develop
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
          hide-badge: true
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: true
```
