### ISSUE TITLE
Cannot read property 'all' of undefined

### ISSUE THREAD

**Issue by MarcAragones** [MishaKav/pytest-coverage-comment#70]
Hi, I'm starting to use this action comment but I'm getting an error:
> Cannot read property 'all' of undefined

Also, the "Base commit" for the changes is `0000...`

This is my configuration in the workflow file:
```yml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    pytest-coverage-path: pytest-coverage.txt
    report-only-changed-files: true
    junitxml-path: pytest-coverage.xml
```

And this is the log in Github Actions:

```
Run MishaKav/pytest-coverage-comment@main
  with:
    pytest-coverage-path: pytest-coverage.txt
    report-only-changed-files: true
    junitxml-path: pytest-coverage.xml
    github-token: ***
    title: Coverage Report
    badge-title: Coverage
    hide-badge: false
    hide-report: false
    hide-comment: false
    create-new-comment: false
    default-branch: main
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.12/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.12/x64/lib
    VENV: .venv/bin/activate
Changed files
  Base commit: 0000000000000000000000000000000000000000
  Head commit: cc8c1b6d8c5
  Error: Not Found
  File read successfully "/home/runner/work/repo-name/repo-name/pytest-coverage.txt"
  Generating coverage report
  Error: Generating coverage report. Cannot read property 'all' of undefined
  File read successfully "/home/runner/work/repo-name/repo-name/pytest-coverage.xml"
  File read successfully "/home/runner/work/repo-name/repo-name/pytest-coverage.xml"
  errors: 0
  
  failures: 1
  
  skipped: 0
  
  tests: 13
  
  time: 4.13

  File read successfully "/home/runner/work/repo-name/repo-name/pytest-coverage.xml"
```
