### ISSUE TITLE
Remove readme linkage

### ISSUE THREAD

**Issue by kankoyan** [MishaKav/pytest-coverage-comment#74]
Hi, is there any config to remove the linkage between readme and the tag?
<img width="108" alt="image" src="https://user-images.githubusercontent.com/97464002/183549658-48ad0246-79fd-4992-8a2e-3dea236ad985.png">

**Comment by MishaKav** [comment]
Just added the config that you asked for, you can use:

```yaml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    remove-link-from-badge: true 
```
or use specific version
```yaml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@v1.1.31
  with:
    remove-link-from-badge: true 
```
