### ISSUE TITLE
Coverage report does not show when multi file input

### ISSUE THREAD

**Issue by kankoyan** [MishaKav/pytest-coverage-comment#77]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/97464002/183795276-a3630acd-66a6-41a7-931d-9d8358bb3b74.png">

<img width="157" alt="image" src="https://user-images.githubusercontent.com/97464002/183795123-a01f14a5-936e-43b7-b89f-6724397a670b.png">

**Comment by kankoyan** [comment]
or am I doing sth incorrect?

**Comment by MishaKav** [comment]
It was missing by design, just release a version that fixed that, you can use:

```yaml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
      pytest-coverage-path: ./data/pytest-coverage_4.txt
      multiple-files: |
        title1, ./data/pytest-coverage_4.txt, ./data/pytest_1.xml
```
or use specific version
```yaml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@v1.1.32
  with:
      pytest-coverage-path: ./data/pytest-coverage_4.txt
      multiple-files: |
        title1, ./data/pytest-coverage_4.txt, ./data/pytest_1.xml
```
