### ISSUE TITLE
is there a way to change the coverage file link 

### ISSUE THREAD

**Issue by ganga-relyanceai** [MishaKav/pytest-coverage-comment#80]
in the current implementation href is pointing to
https://github.com/MishaKav/pytest-coverage-comment/blob/0b96302125cf52b56a0859a04dd048cf3707d110/src/parse.js#L324

Is there any way that I can have a custom href link  so that i can point the actual file location in git repository. i am trying to print coverage of multiple folders in the comment

**Comment by MishaKav** [comment]
I don't get you, even if you have different directories in your repo, everything should work fine. Every file that is covered with the test should be pointing to his location.

Just to mention, you also have `coverage-path-prefix: ./some-dir/other-dir` which is useful when you for example run in docker, and move files to other directories.

Or try to provide me with some example, I will see if I can help you.

**Comment by ganga-relyanceai** [comment]
I have folder1, folder2  each have test. 

folder1 has test docker which will print output in /tmp/pytest-coverage_folder1.txt 
folder2 has another test docker which will print output in /tmp/pytest-coverage_folder2.txt. 

I am trying the multiline output 
```
 name: Pytest coverage comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    multiple-files: |
      My Title 1,/tmp/pytest-coverage_folder1.txt , /tmp/pytest_1.xml
      My Title 2, /tmp/pytest-coverage_folder2.txt /tmp/pytest_2.xml
```
in this case i am seeing that /tmp/pytest-coverage_folder1.txt and /tmp/pytest-coverage_folder2.txt are not processed and not shown in the dialog i am seeing only following 
![image](https://user-images.githubusercontent.com/93580462/185625392-6b2b5e4c-483b-4dd4-a177-86d4b24358fd.png)

coverage report is not shown 
is there a way that I can  see coverage reports for each folders

**Comment by MishaKav** [comment]
Now I get you. It is impossible to generate `coverage-report` for multiple files in one single comment. 
You can see #77 for discussion and suggestions.

If you want just to link the title from `multiple-files` to a specific directory, you can provide a dynamic link for it, in HTML or markdown:

```yaml
 name: Pytest coverage comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    multiple-files: |
      <a href="my_custom_link_here">Title 1</a>, /tmp/pytest-coverage_folder1.txt , /tmp/pytest_1.xml
      [My Title2](https://example.com/my_link_2), /tmp/pytest-coverage_folder2.txt, /tmp/pytest_2.xml
```
