### ISSUE TITLE
Duplicated coverage badge

### ISSUE THREAD

**Issue by erikdenisrs97** [MishaKav/pytest-coverage-comment#82]
writing to readme is occurring twice. anyone to help me?

my push.yml:

```
    - name: Pytest coverage comment
      if: ${{ github.ref == 'refs/heads/main' }}
      id: coverageComment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: pytest-coverage.txt

    - name: Update Readme with Coverage Html
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n${{ steps.coverageComment.outputs.summaryReport }}\n<!-- Pytest Coverage Comment:End -->' ./README.md

    - name: Commit & Push changes to Readme
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions-js/push@master
      with:
        message: Update coverage on Readme
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

issue image:

![image](https://user-images.githubusercontent.com/22759244/187337866-73a036f3-c89f-46e0-ba7e-d6729c5fd828.png)

**Comment by MishaKav** [comment]
Can you please send me the "source" of Readme.md.
I think, maybe you put the "first badge" by yourself and it's not inside the comments 
`<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->`

**Comment by MishaKav** [comment]
@erikdenisrs97 any updates?

**Comment by donheshanthaka** [comment]
Actually i am having the same issue on my end as well, here is the [README.md](https://github.com/donheshanthaka/Price-Finder-Flask-API/blob/main/README.md)

**Comment by isFakeAccount** [comment]
I have the same issue as well. This is my comment for putting HTML in readme.

```yaml
      - name: Update Readme with Coverage Html
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n${{ steps.coverageComment.outputs.summaryReport }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
```

Link to CI file: https://github.com/isFakeAccount/psnawp/blob/testing/.github/workflows/code_coverage.yaml

**Comment by isFakeAccount** [comment]
@erikdenisrs97 `MishaKav/pytest-coverage-comment@v1.1.29` version works fine for me. I'd recommend switching over to that until the bug is resolved.

**Comment by MishaKav** [comment]
@erikdenisrs97  I found the issue. No version was released because the error was only in syntax.
Please update your code from this:

```yaml
- name: Update Readme with Coverage Html
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n${{ steps.coverageComment.outputs.summaryReport }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
```
to this:
```yaml
- name: Update Readme with Coverage Html
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
```

**Comment by MishaKav** [comment]
@isFakeAccount I found the issue. No version was released because the error was only in syntax.
Please update your code from this:

```yaml
      - name: Update Readme with Coverage Html
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n${{ steps.coverageComment.outputs.summaryReport }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
```
to this:
```yaml
      - name: Update Readme with Coverage Html
        run: |
          sed -i '/<!-- Pytest Coverage Comment:Begin -->/,/<!-- Pytest Coverage Comment:End -->/c\<!-- Pytest Coverage Comment:Begin -->\n\${{ steps.coverageComment.outputs.coverageHtml }}\n<!-- Pytest Coverage Comment:End -->' ./README.md
```
