### ISSUE TITLE
Warning in Summary if coverage.xml is used

### ISSUE THREAD

**Issue by drakulavich** [MishaKav/pytest-coverage-comment#83]
Thank you for the great action.

I've added to my GitHub workflow:
```
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
```

But CI is complaining about `pytest-coverage.txt` which is not expected, I suppose.

```
File "/home/runner/work/REPO_NAME/./pytest-coverage.txt" doesn't exist
```
